# Generated by Django 5.2.13 on 2026-04-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="complaint",
            table="complaint_tbl",
        ),
    ]
